export const paths = {
  home: '/',
  forget: '/forget',
  signUp: '/sign-up.html',
  login: '/sign-in.html',
  skinAnalysis: '/skin-analysis.html',
  bookConsultation: '/book-consultation.html',
  consultationForm: '/consultation-form.html',
  productPage: 'product-page.html',
  productListingAtoZ: '/product-listing-a-z.html',
  shopTheGarden: '/shop-the-garden.html',
  writeReview: '/writereview.html',
  accountSetting: '/account-settings.html',
  checkout: '/checkout.html',
  thankYou: '/thank-you-order.html',
  thank_you: '/thank-you.html',
  cart: '/shopping-cart.html',
  wishList: '/wishlist.html',
  orders: '/order-and-returns.html',
  ordersHistory: '/order-history.html',
  ordersHistoryDetail: '/order-history-details.html',
  orderDetail: '/order-details.html',
  paymentMethods: '/payment-methods.html',
  address: '/address.html',
  gifts: '/gift-cards.html',
  gift_certificate_details: '/gift-certificate-details.html',
  deleteAccount: '/delete-account.html',
  closeAccountSuccess: '/account-successfully-closed.html',
  mailto: 'mailto',
  blog: '/blog.html',
  productReview: '/product-review.html',
  changesPassword: '/email-password.html',
  helpCentre: '/help-centre.html',
  trackPackage: '/track-your-package',
  orderReturn: '/order-return.html',
  invoicePage: '/invoice.html',
  searchProductListing: '/search/result',
  usdaZones: 'usdazones',
  plantFinder: '/plant-finder.html',
  faq: '/faq.html',
  contactUs: '/contact-us.html',
  orderConfirmReturn: '/order-and-returns-confirm-your-return.html',
  BOOKCONSULT: '/book-consultation.html',
  orderAndShipping: '/ordering-shipping.html',
  findUsdaZones: '/find-your-usda-zone.html',
  orderFreeCatalog: '/order-free-catalog.html',
  newProducts: '/new.html',
};

export const imageFolder = {
  folderPath: 'storagemedia/1/store/5/images',
};
export const __SpecialBreadCrumbsPaths = [
  {
    path: [paths.cart],
    directTo: null,
    name: 'Cart',
  },
  {
    path: [paths.checkout],
    directTo: null,
    name: 'Checkout',
  },
  {
    path: [paths.orderConfirmReturn],
    directTo: null,
    name: 'Confirm Your Return',
  },
];
